# Generated by Django 5.2.7 on 2026-07-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_name', models.CharField(max_length=100)),
                ('int_size', models.BigIntegerField()),
                ('vchr_purpose', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='app_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_name', models.CharField(max_length=100)),
                ('int_phone', models.CharField(max_length=100)),
                ('vchr_place', models.CharField(max_length=100)),
                ('fk_LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.CharField(max_length=100)),
                ('to_time', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('fk_ROOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.room')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_purpose', models.CharField(max_length=100)),
                ('fk_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.app_user')),
                ('fk_SCHEDULE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.schedule')),
            ],
        ),
    ]
