# Generated by Django 5.2.7 on 2026-07-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='int_rent',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
