# Generated by Django 5.2.7 on 2026-07-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
